valist-io/valist-js

.vscode/settings.json
packages/evm-contracts/contracts/ERC-1155/ProofOfContribution.sol
packages/evm-contracts/contracts/IValist.sol
packages/evm-contracts/contracts/Valist.sol
packages/evm-contracts/test/ERC-1155/ProofOfContribution.ts
packages/evm-contracts/test/index.ts

Proof of Contribution Contract

---

docker-compose.yml
packages/evm-contracts/hardhat.config.ts
packages/evm-contracts/package.json
packages/evm-subgraph/package.json

Run a full local environment with docker-compose.
```bash
docker-compose up
lerna run deploy:local
```

create docker-compose for full environment.

---

packages/evm-subgraph/config/polygon.json
packages/evm-subgraph/package.json
packages/valist-sdk/src/contract/evm.ts
packages/valist-sdk/src/contract/metatx.ts

Deployment to Polygon mainnet!

Polygon deployment

---

packages/valist-web/components/Accounts/AccountContext.tsx
packages/valist-web/components/Homepage/HomepageContent.tsx
packages/valist-web/components/Homepage/HomepageProfileCard.tsx
packages/valist-web/components/Licenses/LicenseList.tsx
packages/valist-web/components/Navbar/Navbar.tsx
packages/valist-web/components/Projects/ProjectActions.tsx
packages/valist-web/components/Publishing/CreateTeamForm.tsx
packages/valist-web/components/Publishing/TeamContent.tsx
packages/valist-web/package-lock.json
packages/valist-web/package.json
packages/valist-web/pages/[teamName]/[projectName]/index.tsx
packages/valist-web/pages/_app.tsx
packages/valist-web/pages/create.tsx
packages/valist-web/pages/index.tsx
packages/valist-web/utils/Account/types.ts
packages/valist-web/utils/Providers/index.ts
packages/valist-web/utils/Validation/index.ts

Co-authored-by: Free Spirit <jiyuu-jin@users.noreply.github.com>

better team form validation + ens resolution + various ux tweaks

---

packages/valist-web/components/Publishing/CreateLicenseForm.tsx
packages/valist-web/components/Publishing/CreateProjectForm.tsx
packages/valist-web/components/Publishing/CreateReleaseForm.tsx
packages/valist-web/components/Publishing/CreateTeamForm.tsx
packages/valist-web/pages/create.tsx
packages/valist-web/utils/Providers/index.ts

Co-authored-by: Free Spirit <jiyuu-jin@users.noreply.github.com>

Magic + WalletConnect fix, various UX improvements

---

Makefile
packages/valist-cli/src/index.ts
packages/valist-web/components/Accounts/AccountPicker.tsx
packages/valist-web/components/Homepage/HomepageContent.tsx
packages/valist-web/components/Homepage/HomepageProfileCard.tsx
packages/valist-web/components/Projects/ProjectContent.tsx
packages/valist-web/pages/_app.tsx
packages/valist-web/pages/create.tsx
packages/valist-web/pages/index.tsx
packages/valist-web/utils/Account/index.ts
packages/valist-web/utils/Apollo/normalization.ts
packages/valist-web/utils/Apollo/queries.ts
packages/valist-web/utils/Valist/types.ts

Co-authored-by: Alec M. Wantoch <awantoch@users.noreply.github.com>

Added account dropdown to homepage and account fixes to create form.

---

packages/valist-web/features/accounts/ManageAccount.tsx
packages/valist-web/features/accounts/forms/AccountFormContent.tsx

Fix account creation not redirecting to members form.

---

packages/valist-cli/src/commands/gen.ts
packages/valist-cli/src/commands/keygen.ts

Add valist keygen command

---

packages/valist-web/components/Layouts/Header.tsx

Add address and ENS support to search

---

packages/valist-cli/README.md
packages/valist-cli/package-lock.json
packages/valist-cli/package.json

CLI v2.3.1

---

packages/valist-sdk/src/client.ts
packages/valist-web/forms/create-account.tsx
packages/valist-web/forms/create-project.tsx
packages/valist-web/forms/create-release.tsx
packages/valist-web/forms/update-account.tsx
packages/valist-web/forms/update-project.tsx
packages/valist-web/forms/utils.tsx

Add IPFS upload status notifications

---

packages/valist-ui/src/components/Button/Button.tsx
packages/valist-web/components/AddressInput/AddressInput.tsx

Add submit button to AddressInput on add member pages

---

packages/valist-sdk/src/types.ts
packages/valist-web/pages/-/account/[account]/project/[project]/create/release.tsx

Add android_arm64 platform

---

packages/valist-web/graphql/Discover.graphql
packages/valist-web/pages/-/discover.tsx

Only displays apps with releases on Discovery page

Filter by released on discovery page

---

packages/valist-web/components/Activity/Activity.tsx
packages/valist-web/components/ApolloProvider/ApolloProvider.tsx
packages/valist-web/components/CreateAccount/CreateAccount.tsx
packages/valist-web/components/CreateProject/CreateProject.tsx
packages/valist-web/components/DonationModal/DonationModal.tsx
packages/valist-web/components/ValistProvider/ValistProvider.tsx
packages/valist-web/components/WagmiProvider/WagmiProvider.tsx
packages/valist-web/next.config.js
packages/valist-web/pages/-/account/[account]/project/[project]/checkout.tsx
packages/valist-web/pages/-/account/[account]/project/[project]/create/release.tsx
packages/valist-web/pages/-/account/[account]/project/[project]/pricing.tsx
packages/valist-web/pages/-/account/[account]/project/[project]/settings.tsx
packages/valist-web/pages/-/account/[account]/settings.tsx
packages/valist-web/pages/[account]/[project]/index.tsx
packages/valist-web/pages/[account]/[project]/launch.tsx
packages/valist-web/pages/[account]/index.tsx
packages/valist-web/utils/config.ts

Set `CHAIN_ID` in `next.config` to set network.
Closes #236

disable network switching

---

packages/valist-ui/src/components/Carousel/CarouselItem.tsx
packages/valist-web/pages/-/discover.tsx

Adds the following sections:
- Featured Games
- Featured dApps
- Featured on Testnet
Turns "Latest" => "Newest" on new apps section

Add featured games, dapps, and on testnet to Discovery

---

packages/valist-web/forms/common.ts

For new accounts and projects, remove the ability to add an underscore. This helps with automatic subdomain support as well as future namespace improvements.
Also remove unused regex variables.

remove _ from allowed characters

---

.github/workflows/sapphire-desktop.yml
Makefile
electron/electron-builder.config.json
electron/package-lock.json
electron/package.json
electron/src/index.ts
package.json
packages/valist-web/utils/config.ts

Sapphire macOS releases

---

packages/valist-web/pages/-/account/[account]/project/[project]/deployments.tsx

Fix deploy success message

---

package-lock.json
packages/valist-ui/src/components/MemberCard/MemberCard.tsx
packages/valist-web/components/AccountSelect/AccountSelect.tsx
packages/valist-web/components/AccountSelect/index.ts
packages/valist-web/graphql/Dashboard.graphql
packages/valist-web/pages/-/activity.tsx
packages/valist-web/pages/-/dashboard.tsx
packages/valist-web/pages/-/members.tsx
packages/valist-web/utils/dashboard.ts

account select fixes

---

packages/valist-web/components/ApolloProvider/cache.ts
packages/valist-web/forms/events.ts
packages/valist-web/graphql/fragments/AccountCreated.graphql
packages/valist-web/graphql/fragments/AccountMembers.graphql
packages/valist-web/graphql/fragments/AccountProjects.graphql
packages/valist-web/graphql/fragments/ProjectMembers.graphql
packages/valist-web/graphql/fragments/ProjectReleases.graphql
packages/valist-web/graphql/fragments/UserAccounts.graphql
packages/valist-web/pages/[account]/[project]/index.tsx
packages/valist-web/pages/[account]/index.tsx

Bug/optimistic UI

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs_report.yml

Add issue template

---

packages/valist-cli/src/commands/download.ts
packages/valist-sdk/src/index.ts
packages/valist-sdk/tests/client.spec.ts

IPFS Migration

---

packages/valist-sdk/src/types.ts
packages/valist-ui/src/components/FileButton/FileButton.tsx
packages/valist-ui/src/components/PlatformInput/PlatformInput.stories.tsx
packages/valist-ui/src/components/PlatformInput/PlatformInput.styles.ts
packages/valist-ui/src/components/PlatformInput/PlatformInput.tsx
packages/valist-ui/src/components/PlatformInput/index.tsx
packages/valist-ui/src/index.ts
packages/valist-web/forms/create-release.tsx
packages/valist-web/pages/-/account/[account]/project/[project]/create/release.tsx

Updates platform metadata to include executable paths for compressed builds

Platform executable inputs

---

package-lock.json
packages/valist-sdk/package.json

SDK v2.9.1

---

packages/valist-sdk/package.json
packages/valist-sdk/src/types.ts

Supports arbitrary platform keys for upload. The api type is still typed according to the platform keys limited to be used by HyperPlay

[Feat] Support pinning with generic platform keys

---

package-lock.json
packages/valist-sdk/package.json
packages/valist-sdk/src/metatx.ts

Migrates to a Defender 2.0 Action with latest runtime

[Tech] Upgrade to OpenZeppelin Defender 2.0

---

packages/valist-sdk/package.json
packages/valist-sdk/src/typesApi.ts

Add booleans returned on listings endpoint.
Make quests prop optional as it is not being used

[Update] listing api type
